import {Inter} from 'next/font/google';
import StyledComponentsRegistry from '../lib/AntdRegistry';
import {Metadata} from "next";
import '@/styles/globals.css'
import SessionProvider from '../lib/SessionProvider';
import {getServerSession} from "next-auth";
import {ReactNode} from "react";
import authOptions from '@/lib/authOptions';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


const RootLayout = async ({children}: {
    children: ReactNode
}) => {
    const session = await getServerSession(authOptions)

    return (
        <html lang="en">
            <body className={inter.className}>
                <StyledComponentsRegistry>
                    <SessionProvider session={session}>
                        {children}
                    </SessionProvider>
                </StyledComponentsRegistry>
            </body>
        </html>
    )
};

export default RootLayout;
